In [1]:
import pandas as pd

movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")
tags = pd.read_csv("tags.csv")
links = pd.read_csv("links.csv")

In [2]:
print("MOVIES")
movies.info()

print("\nRATINGS")
ratings.info()

print("\nTAGS")
tags.info()

print("\nLINKS")
links.info()

MOVIES
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

RATINGS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

TAGS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3683 entries, 0 to 3682
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userId     3683 non-null   int64
 1   movieId    3683 non-null   int64
 2   tag        3683 non-null   object
 3   timestamp  3683 non-null   int64
dtypes: int64(3), object(1)
memory usage: 115.2+ KB

LINKS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   imdbId   9742 non-null   int64
 2   tmdbId   9734 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 228.5 KB

In [3]:
print("MOVIES")
print(movies.describe())

print("\nRATINGS")
print(ratings.describe())

print("\nTAGS")
print(tags.describe())

print("\nLINKS")
print(links.describe())

MOVIES
             movieId
count    9742.000000
mean    42200.353623
std     52160.494854
min         1.000000
25%      3248.250000
50%      7300.000000
75%     76232.000000
max    193609.000000

RATINGS
              userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

TAGS
            userId        movieId     timestamp
count  3683.000000    3683.000000  3.683000e+03
mean    431.149335   27252.013576  1.320032e+09
std     158.472553   43490.558803  1.721025e+08
min       2.000000       1.000000  1.137179e+09
25%     424.000000    1262.500000  1.137521e+09
50%     474.000000    4454.000000  1.269833e+09
75%     477.000000   39263.000000  1.498457e+09
max     610.000000  193565.000000  1.537099e+09

LINKS
             movieId        imdbId         tmdbId
count    9742.000000  9.742000e+03    9734.000000
mean    42200.353623  6.771839e+05   55162.123793
std     52160.494854  1.107228e+06   93653.481487
min         1.000000  4.170000e+02       2.000000
25%      3248.250000  9.518075e+04    9665.500000
50%      7300.000000  1.672605e+05   16529.000000
75%     76232.000000  8.055685e+05   44205.750000
max    193609.000000  8.391976e+06  525662.000000

In [4]:
print("Missing values in movies:")
print(movies.isnull().sum())

print("\nMissing values in ratings:")
print(ratings.isnull().sum())

print("\nMissing values in tags:")
print(tags.isnull().sum())

print("\nMissing values in links:")
print(links.isnull().sum())

Missing values in movies:
movieId    0
title      0
genres     0
dtype: int64

Missing values in ratings:
userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

Missing values in tags:
userId       0
movieId      0
tag          0
timestamp    0
dtype: int64

Missing values in links:
movieId    0
imdbId     0
tmdbId     8
dtype: int64

In [5]:
print("تعداد movieId تکراری:")
print(movies["movieId"].duplicated().sum())

print("تعداد title تکراری:")
print(movies["title"].duplicated().sum())

movies[movies["title"].duplicated(keep=False)].sort_values("title")

تعداد movieId تکراری:
0
تعداد title تکراری:
5

,movieId,title,genres
4169,6003,Confessions of a Dangerous Mind (2002),Comedy|Crime|Drama|Thriller
9106,144606,Confessions of a Dangerous Mind (2002),Comedy|Crime|Drama|Romance|Thriller
650,838,Emma (1996),Comedy|Drama|Romance
5601,26958,Emma (1996),Romance
5854,32600,Eros (2004),Drama
9135,147002,Eros (2004),Drama|Romance
2141,2851,Saturn 3 (1980),Adventure|Sci-Fi|Thriller
9468,168358,Saturn 3 (1980),Sci-Fi|Thriller
5931,34048,War of the Worlds (2005),Action|Adventure|Sci-Fi|Thriller
6932,64997,War of the Worlds (2005),Action|Sci-Fi

In [6]:
genres = movies["genres"].str.split("|").explode()

print(genres.value_counts())

genres
Drama                 4361
Comedy                3756
Thriller              1894
Action                1828
Romance               1596
Adventure             1263
Crime                 1199
Sci-Fi                 980
Horror                 978
Fantasy                779
Children               664
Animation              611
Mystery                573
Documentary            440
War                    382
Musical                334
Western                167
IMAX                   158
Film-Noir               87
(no genres listed)      34
Name: count, dtype: int64

In [7]:
movies[movies["genres"] == "(no genres listed)"]

,movieId,title,genres
8517,114335,La cravate (1957),(no genres listed)
8684,122888,Ben-hur (2016),(no genres listed)
8687,122896,Pirates of the Caribbean: Dead Men Tell No Tal...,(no genres listed)
8782,129250,Superfast! (2015),(no genres listed)
8836,132084,Let It Be Me (1995),(no genres listed)
8902,134861,Trevor Noah: African American (2013),(no genres listed)
9033,141131,Guardians (2016),(no genres listed)
9053,141866,Green Room (2015),(no genres listed)
9070,142456,The Brand New Testament (2015),(no genres listed)
9091,143410,Hyena Road,(no genres listed)
9138,147250,The Adventures of Sherlock Holmes and Doctor W...,(no genres listed)
9178,149330,A Cosmic Christmas (1977),(no genres listed)
9217,152037,Grease Live (2016),(no genres listed)
9248,155589,Noin 7 veljestä (1968),(no genres listed)
9259,156605,Paterson,(no genres listed)
9307,159161,Ali Wong: Baby Cobra (2016),(no genres listed)
9316,159779,A Midsummer Night's Dream (2016),(no genres listed)
9348,161008,The Forbidden Dance (1990),(no genres listed)
9413,165489,Ethel & Ernest (2016),(no genres listed)
9426,166024,Whiplash (2013),(no genres listed)
9448,167570,The OA,(no genres listed)
9478,169034,Lemonade (2016),(no genres listed)
9514,171495,Cosmos,(no genres listed)
9515,171631,Maria Bamford: Old Baby,(no genres listed)
9518,171749,Death Note: Desu nôto (2006–2007),(no genres listed)
9525,171891,Generation Iron 2,(no genres listed)
9534,172497,T2 3-D: Battle Across Time (1996),(no genres listed)
9541,172591,The Godfather Trilogy: 1972-1990 (1992),(no genres listed)
9562,173535,The Adventures of Sherlock Holmes and Doctor W...,(no genres listed)
9573,174403,The Putin Interviews (2017),(no genres listed)
9611,176601,Black Mirror,(no genres listed)
9661,181413,Too Funny to Fail: The Life and Death of The D...,(no genres listed)
9663,181719,Serving in Silence: The Margarethe Cammermeyer...,(no genres listed)
9669,182727,A Christmas Story Live! (2017),(no genres listed)

In [8]:
movies["genres_clean"] = movies["genres"].str.split("|")

In [9]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb=MultiLabelBinarizer()
genre_matrix=mlb.fit_transform(movies["genres_clean"])

In [10]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix=cosine_similarity(genre_matrix)

In [11]:
movie_title = "Toy Story (1995)"
movie_index = movies[movies["title"] == movie_title].index[0]

print(movie_index)

0

In [12]:
similarity_score=list(
    enumerate(similarity_matrix[movie_index]
))
#print(similarity_score)
similarity_score=sorted(
    similarity_score,key=lambda x: x[1],
    reverse=True)

Film=similarity_score[1:11]
for index, score in Film:
    print(
        movies.iloc[index]["title"],
        "→",
        round(score, 3)
    )

Antz (1998) → 1.0
Toy Story 2 (1999) → 1.0
Adventures of Rocky and Bullwinkle, The (2000) → 1.0
Emperor's New Groove, The (2000) → 1.0
Monsters, Inc. (2001) → 1.0
Wild, The (2006) → 1.0
Shrek the Third (2007) → 1.0
Tale of Despereaux, The (2008) → 1.0
Asterix and the Vikings (Astérix et les Vikings) (2006) → 1.0
Turbo (2013) → 1.0

In [13]:
tags_grouped = tags.groupby("movieId")["tag"].apply(
    lambda x: " ".join(x)
).reset_index()

In [14]:
movies = movies.merge(
    tags_grouped,
    on="movieId",
    how="left"
)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
movies["tag"] = movies["tag"].fillna("")
tfidf = TfidfVectorizer()
tag_matrix = tfidf.fit_transform(movies["tag"])
print(tag_matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5260 stored elements and shape (9742, 1744)>
  Coords	Values
  (0, 1186)	0.9013892751944387
  (0, 609)	0.43300967028975734
  (1, 548)	0.2993223617805401
  (1, 952)	0.30779663656179057
  (1, 187)	0.3604436401370177
  (1, 617)	0.6900907574071948
  (1, 1307)	0.3341201383494041
  (1, 1714)	0.31286772961538223
  (2, 1023)	0.7071067811865475
  (2, 1120)	0.7071067811865475
  (4, 1216)	0.7306025829401581
  (4, 1279)	0.6828029480026938
  (6, 1279)	1.0
  (10, 1200)	0.647970747235599
  (10, 1219)	0.7616652222117927
  (13, 1200)	0.647970747235599
  (13, 1219)	0.7616652222117927
  (15, 950)	1.0
  (16, 837)	0.7071067811865476
  (16, 116)	0.7071067811865476
  (20, 736)	1.0
  (21, 1379)	0.7160446667214553
  (21, 879)	0.6980544643935458
  (24, 50)	1.0
  (25, 1389)	1.0
  :	:
  (9656, 1057)	0.7071067811865475
  (9656, 133)	0.7071067811865475
  (9681, 610)	0.43679739296587655
  (9681, 329)	0.3981323048895053
  (9681, 1252)	0.5407691201106816
  (9681, 977)	0.5985544787538583
  (9692, 617)	0.41010290371282654
  (9692, 37)	0.3514568786765225
  (9692, 1660)	0.39711773402341
  (9692, 53)	0.4284044724795235
  (9692, 1663)	0.4284044724795235
  (9692, 28)	0.4284044724795235
  (9709, 1339)	0.4241751573500051
  (9709, 1328)	0.4241751573500051
  (9709, 1291)	0.4241751573500051
  (9709, 859)	0.4797011088486741
  (9709, 214)	0.4797011088486741
  (9710, 1464)	0.47295618198083866
  (9710, 1682)	0.5011313306230039
  (9710, 308)	0.5011313306230039
  (9710, 502)	0.5234952042398695
  (9732, 329)	0.37858441135716725
  (9732, 80)	0.4569177580743748
  (9732, 640)	0.5691660591750155
  (9732, 1280)	0.5691660591750155

In [16]:
from scipy.sparse import hstack
combined_matrix=hstack([genre_matrix,tag_matrix])

In [17]:
similarity_matrix = cosine_similarity(combined_matrix)
#print(similarity_matrix)

In [18]:
rating_stats = ratings.groupby("movieId").agg(
    avg_rating=("rating", "mean"),
    rating_count=("rating", "count")
).reset_index()
#print(rating_stats)

In [19]:
movies = movies.merge(
    rating_stats,
    on="movieId",
    how="left"
)

In [20]:
movies.head(2)

,movieId,title,genres,genres_clean,tag,avg_rating,rating_count
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"[Adventure, Animation, Children, Comedy, Fantasy]",pixar pixar fun,3.920930,215.0
1,2,Jumanji (1995),Adventure|Children|Fantasy,"[Adventure, Children, Fantasy]",fantasy magic board game Robin Williams game,3.431818,110.0

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

rating_matrix = scaler.fit_transform(
    movies[["avg_rating", "rating_count"]]
)

In [22]:
#print(rating_matrix[:5])

In [23]:
from scipy.sparse import hstack

combined_matrix = hstack([
    genre_matrix,
    tag_matrix,
    rating_matrix
])

In [24]:
movie_title = "Toy Story (1995)"
movie_index = movies[movies["title"] == movie_title].index[0]

In [25]:
similarity_score=list(
    enumerate(similarity_matrix[movie_index]
))
#print(similarity_score)
similarity_score=sorted(
    similarity_score,key=lambda x: x[1],
    reverse=True)

Film=similarity_score[1:11]
for index, score in Film:
    print(
        movies.iloc[index]["title"],
        "→",
        round(score, 3)
    )

Toy Story 2 (1999) → 0.93
Antz (1998) → 0.913
Adventures of Rocky and Bullwinkle, The (2000) → 0.913
Emperor's New Groove, The (2000) → 0.913
Monsters, Inc. (2001) → 0.913
Wild, The (2006) → 0.913
Shrek the Third (2007) → 0.913
Tale of Despereaux, The (2008) → 0.913
Asterix and the Vikings (Astérix et les Vikings) (2006) → 0.913
Turbo (2013) → 0.913

In [26]:
print(movies[["avg_rating", "rating_count"]].isna().sum())

avg_rating      18
rating_count    18
dtype: int64

In [27]:
movies[["avg_rating", "rating_count"]] = movies[
    ["avg_rating", "rating_count"]
].fillna(0)

In [28]:
scaler = StandardScaler()

rating_matrix = scaler.fit_transform(
    movies[["avg_rating", "rating_count"]]
)

In [29]:
from sklearn.preprocessing import normalize
from scipy.sparse import csr_matrix

genre_norm = normalize(genre_matrix)
tag_norm = normalize(tag_matrix)
rating_norm = normalize(csr_matrix(rating_matrix))

In [30]:
weighted_matrix = hstack([
    genre_norm * 0.4,
    tag_norm * 0.4,
    rating_norm * 0.2
])

In [31]:
#پیشنهاد فیلم به کاربر بر اساس سلیقه مشابه کاربر هایی که
#چند فیلم را دیدن و رای یکسانی به انها دادن

In [32]:
#اابتدا باید جدولی بسازیم که
#سطر های ان کاربران و ستون های ان فیلم ها و داخل سلول ها
#نظرات کاربر به ان فیلم ها باشد

In [33]:
user_movie_matrix=ratings.pivot_table(
    index="userId",
    columns="movieId",
    values="rating"
)

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

user_similarity = cosine_similarity(
    user_movie_matrix.fillna(0)
)

print(user_similarity)

[[1.         0.02728287 0.05972026 ... 0.29109737 0.09357193 0.14532081]
 [0.02728287 1.         0.         ... 0.04621095 0.0275654  0.10242675]
 [0.05972026 0.         1.         ... 0.02112846 0.         0.03211875]
 ...
 [0.29109737 0.04621095 0.02112846 ... 1.         0.12199271 0.32205486]
 [0.09357193 0.0275654  0.         ... 0.12199271 1.         0.05322546]
 [0.14532081 0.10242675 0.03211875 ... 0.32205486 0.05322546 1.        ]]

In [35]:
user_id = 1

user_index = user_movie_matrix.index.get_loc(user_id)

similar_users = list(
    enumerate(user_similarity[user_index])
)

similar_users = sorted(
    similar_users,
    key=lambda x: x[1],
    reverse=True
)

similar_users = similar_users[1:11]

for index, score in similar_users:
    similar_user_id = user_movie_matrix.index[index]
    
    print(
        "User:", similar_user_id,
        "→",
        round(score, 3)
    )

User: 266 → 0.357
User: 313 → 0.352
User: 368 → 0.345
User: 57 → 0.345
User: 91 → 0.335
User: 469 → 0.331
User: 39 → 0.33
User: 288 → 0.33
User: 452 → 0.328
User: 45 → 0.328

In [36]:
#ابتدا این ۱۰ نفر را وارد یک لیست میکنیم
top_10_users = []

for index, similarity in similar_users:
    similar_user_id = user_movie_matrix.index[index]
    
    top_10_users.append(similar_user_id)

print(top_10_users)

[np.int64(266), np.int64(313), np.int64(368), np.int64(57), np.int64(91), np.int64(469), np.int64(39), np.int64(288), np.int64(452), np.int64(45)]

In [37]:
#فیلم هایی ک این ۱۰ نفر دیده اند را جمع میکنیم در یک لیست
candidate_movies = []
for user_id in top_10_users:
    user_movies = user_movie_matrix.loc[user_id].dropna().index
    candidate_movies.extend(user_movies)

In [38]:
#فیلم هایی ک کاربر یک دیده را از اون لیست پاک میکنیم
user_1_movies = user_movie_matrix.loc[1].dropna().index
new_candidate_movies = []

for movie_id in candidate_movies:
    
    if movie_id not in user_1_movies:
        
        new_candidate_movies.append(movie_id)
print(new_candidate_movies)

[16, 17, 21, 24, 32, 39, 45, 64, 69, 95, 132, 135, 145, 198, 288, 353, 368, 377, 440, 474, 476, 493, 514, 541, 551, 555, 589, 694, 778, 785, 924, 1036, 1079, 1093, 1171, 1199, 1200, 1215, 1242, 1259, 1261, 1266, 1285, 1288, 1297, 1356, 1374, 1375, 1376, 1394, 1405, 1466, 1476, 1485, 1527, 1597, 1610, 1614, 1641, 1663, 1722, 1772, 1784, 1866, 1883, 1884, 1911, 1912, 1923, 1968, 2064, 2097, 2167, 2194, 2195, 2249, 2278, 2288, 2300, 2302, 2321, 2355, 2384, 2396, 2428, 2471, 2490, 2539, 2560, 2599, 2605, 2683, 2702, 2706, 2710, 2712, 2770, 2791, 2804, 2812, 2863, 2890, 2918, 2968, 3016, 3020, 3039, 3060, 3108, 3113, 3142, 3156, 3265, 10, 29, 32, 39, 76, 165, 170, 172, 188, 196, 253, 293, 318, 332, 353, 377, 379, 380, 382, 405, 442, 474, 512, 519, 541, 589, 610, 737, 750, 858, 866, 880, 912, 920, 924, 968, 991, 999, 1036, 1037, 1047, 1059, 1125, 1129, 1199, 1200, 1212, 1215, 1221, 1235, 1247, 1249, 1261, 1274, 1285, 1287, 1301, 1320, 1339, 1344, 1345, 1347, 1350, 1356, 1371, 1372, 1374, 1375, 1376, 1387, 1391, 1394, 1405, 1449, 1466, 1480, 1513, 1590, 1591, 1603, 1608, 1610, 1639, 1653, 1690, 1717, 1748, 1754, 1882, 1885, 1909, 1923, 1968, 1974, 1994, 1997, 2001, 2002, 2003, 2004, 2006, 2011, 2020, 2021, 2023, 2034, 2043, 2053, 2076, 2080, 2087, 2097, 2100, 2109, 2117, 2138, 2140, 2167, 2275, 2287, 2302, 2311, 2363, 2376, 2377, 2407, 2409, 2455, 2467, 2513, 2527, 2530, 2531, 2532, 2533, 2553, 2643, 2664, 2710, 2728, 2746, 2747, 2762, 2791, 2798, 2819, 2867, 2871, 2901, 2918, 2968, 2986, 3032, 3081, 3114, 3153, 3175, 3210, 3256, 3262, 3267, 3396, 3421, 3438, 3471, 3481, 3535, 3550, 3555, 3638, 3688, 3689, 3693, 3697, 3701, 3704, 3708, 3727, 3751, 3753, 3771, 3863, 3889, 3917, 3927, 3930, 3977, 3994, 3996, 4025, 4084, 4085, 4105, 4121, 4128, 4130, 4133, 4148, 4180, 4210, 4226, 4275, 4351, 4370, 4499, 4518, 4553, 4571, 4643, 4799, 4848, 4855, 4865, 4874, 4901, 4915, 4941, 4951, 4980, 4993, 5010, 5026, 5039, 5040, 5214, 5254, 5349, 5378, 5463, 5538, 5539, 5540, 5544, 10, 16, 21, 22, 42, 79, 81, 95, 111, 132, 160, 161, 164, 165, 168, 170, 172, 173, 185, 198, 208, 225, 227, 230, 257, 266, 288, 292, 293, 303, 315, 317, 350, 353, 368, 370, 376, 377, 380, 415, 426, 431, 434, 436, 438, 454, 459, 466, 474, 481, 482, 485, 490, 494, 502, 517, 521, 540, 544, 548, 555, 587, 589, 647, 653, 678, 707, 748, 762, 782, 786, 798, 809, 832, 849, 858, 866, 880, 891, 903, 904, 908, 920, 924, 996, 999, 1035, 1036, 1037, 1047, 1061, 1094, 1100, 1101, 1129, 1179, 1183, 1193, 1200, 1201, 1216, 1221, 1233, 1242, 1250, 1252, 1259, 1262, 1263, 1272, 1304, 1320, 1327, 1343, 1358, 1370, 1371, 1374, 1375, 1378, 1379, 1385, 1387, 1388, 1389, 1391, 1407, 1422, 1431, 1438, 1459, 1466, 1479, 1499, 1515, 1518, 1527, 1544, 1556, 1589, 1590, 1597, 1598, 1608, 1610, 1615, 1616, 1645, 1653, 1673, 1674, 1686, 1687, 1690, 1711, 1722, 1729, 1769, 1772, 1779, 1785, 1792, 1799, 1801, 1831, 1833, 1876, 1892, 1909, 1917, 1918, 1939, 1944, 1953, 1957, 1960, 1965, 1968, 1969, 1994, 1995, 1996, 2001, 2002, 2006, 2009, 2013, 2023, 2027, 2110, 2112, 2118, 2121, 2122, 2126, 2135, 2153, 2167, 2194, 2202, 2231, 2263, 2278, 2288, 2302, 2307, 2322, 2334, 2344, 2347, 2367, 2373, 2391, 2399, 2402, 2403, 2404, 2405, 2409, 2410, 2412, 2455, 2456, 2457, 2468, 2476, 2490, 2505, 2524, 2527, 2530, 2531, 2532, 2533, 2535, 2561, 2605, 2613, 2662, 2668, 2670, 2672, 2688, 2699, 2735, 2762, 2763, 2791, 2792, 2802, 2803, 2808, 2815, 2816, 2817, 2818, 2819, 2871, 2881, 2890, 2941, 2986, 2990, 3005, 3029, 3035, 3063, 3066, 3082, 3102, 3104, 3107, 3113, 3127, 3148, 3160, 3162, 3173, 3197, 3203, 3204, 3208, 3219, 3249, 3256, 3257, 3267, 3272, 3285, 3286, 3298, 3301, 3316, 3354, 3370, 3418, 3420, 3430, 3431, 3432, 3438, 3452, 3476, 3505, 3513, 3519, 3529, 3545, 3555, 3557, 3584, 3623, 3628, 3633, 3635, 3638, 3643, 3654, 3686, 3697, 3698, 3704, 3705, 3706, 3710, 3716, 3724, 3726, 3731, 3753, 3755, 3758, 3763, 3764, 3766, 3767, 3768, 3769, 3810, 3811, 3836, 3841, 3844, 3846, 3869, 3871, 3873, 3877, 3917, 3918, 3922, 3927, 3930, 3957, 3959, 3984, 3985, 4000, 4002, 4007, 4008, 4009, 10, 11, 21, 32, 39, 52, 65, 69, 89, 95, 104, 107, 112, 141, 150, 153, 158, 160, 162, 171, 185, 198, 208, 224, 227, 234, 265, 272, 303, 305, 329, 355, 357, 364, 377, 379, 380, 382, 410, 417, 421, 431, 434, 440, 442, 471, 473, 474, 485, 494, 497, 515, 516, 518, 520, 537, 539, 541, 551, 587, 588, 589, 594, 595, 597, 610, 653, 671, 674, 707, 720, 728, 745, 748, 750, 761, 762, 778, 781, 783, 786, 810, 838, 849, 851, 858, 861, 866, 880, 892, 897, 899, 903, 904, 908, 911, 912, 913, 915, 920, 922, 924, 933, 942, 951, 955, 969, 991, 994, 999, 1027, 1028, 1036, 1047, 1059, 1079, 1094, 1100, 1101, 1129, 1148, 1179, 1183, 1184, 1193, 1200, 1201, 1204, 1212, 1221, 1223, 1234, 1242, 1243, 1248, 1249, 1250, 1252, 1254, 1257, 1266, 1268, 1269, 1274, 1276, 1277, 1283, 1284, 1285, 1287, 1288, 1303, 1304, 1320, 1356, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1378, 1379, 1385, 1388, 1391, 1407, 1416, 1425, 1429, 1441, 1468, 1479, 1498, 1499, 1513, 1518, 1527, 1544, 1562, 1564, 1584, 1590, 1597, 1603, 1608, 1610, 1614, 1616, 1641, 1643, 1646, 1653, 1670, 1673, 1674, 1678, 1682, 1688, 1690, 1704, 1711, 1721, 1722, 1726, 1747, 1748, 1769, 1784, 1831, 1858, 1866, 1882, 1884, 1907, 1909, 1912, 1939, 1953, 1968, 2001, 2002, 2006, 2009, 2019, 2021, 2023, 2067, 2080, 2081, 2083, 2087, 2088, 2100, 2102, 2108, 2109, 2124, 2140, 2150, 2155, 2194, 2202, 2232, 2288, 2289, 2297, 2300, 2301, 2302, 2311, 2321, 2324, 2336, 2354, 2355, 2376, 2390, 2393, 2396, 2403, 2405, 2407, 2429, 2476, 2490, 2530, 2532, 2599, 2605, 2642, 2681, 2683, 2687, 2690, 2701, 2706, 2709, 2723, 2759, 2762, 2770, 2788, 2791, 2802, 2804, 2917, 2918, 2921, 2922, 2935, 2941, 2951, 2961, 2968, 2989, 2990, 3020, 3022, 3030, 3032, 3044, 3045, 3064, 3066, 3070, 3081, 3082, 3104, 3105, 3107, 3108, 3114, 3159, 3160, 3175, 3208, 3255, 3256, 3258, 3259, 3260, 3269, 3272, 3301, 3334, 3361, 3396, 3426, 3429, 3435, 3446, 3466, 3471, 3494, 3500, 3507, 3543, 3552, 3593, 3614, 3624, 3628, 3632, 3635, 3638, 3643, 3681, 3685, 3686, 3697, 3704, 3705, 3753, 3769, 3773, 3774, 3811, 3827, 3835, 3836, 3901, 3937, 2, 10, 16, 19, 21, 22, 25, 29, 32, 36, 39, 41, 58, 88, 92, 95, 104, 111, 112, 150, 153, 158, 160, 161, 165, 172, 173, 185, 186, 196, 208, 225, 236, 251, 252, 253, 266, 288, 292, 293, 315, 318, 322, 329, 337, 344, 350, 353, 357, 364, 368, 370, 374, 376, 377, 380, 384, 410, 420, 428, 432, 433, 434, 435, 442, 454, 464, 466, 471, 474, 482, 485, 494, 502, 515, 520, 533, 539, 541, 551, 555, 586, 587, 588, 589, 594, 595, 597, 606, 610, 628, 653, 678, 708, 741, 745, 750, 778, 784, 786, 799, 802, 832, 842, 858, 866, 903, 904, 908, 912, 920, 924, 1028, 1035, 1036, 1079, 1094, 1101, 1125, 1129, 1148, 1183, 1193, 1199, 1200, 1201, 1207, 1215, 1221, 1225, 1234, 1241, 1242, 1246, 1249, 1253, 1257, 1259, 1261, 1262, 1266, 1274, 1276, 1288, 1297, 1304, 1307, 1321, 1337, 1340, 1347, 1350, 1356, 1358, 1370, 1373, 1374, 1375, 1376, 1380, 1385, 1387, 1391, 1393, 1394, 1405, 1407, 1485, 1527, 1544, 1584, 1608, 1610, 1645, 1653, 1682, 1687, 1704, 1747, 1748, 1760, 1762, 1771, 1845, 1876, 1885, 1909, 1917, 1921, 1923, 1961, 1968, 1974, 1981, 1994, 2001, 2002, 2011, 2019, 2060, 2072, 2076, 2081, 2097, 2100, 2117, 2122, 2138, 2140, 2144, 2146, 2160, 2194, 2236, 2287, 2288, 2289, 2298, 2302, 2355, 2396, 2402, 2403, 2419, 2420, 2431, 2455, 2456, 2463, 2518, 2522, 2598, 2599, 2625, 2651, 2668, 2683, 2699, 2706, 2710, 2712, 2713, 2717, 2723, 2762, 2782, 2784, 2790, 2791, 2804, 2817, 2867, 2868, 2871, 2890, 2918, 2990, 2992, 3000, 3013, 3017, 3018, 3031, 3070, 3081, 3113, 3114, 3153, 3175, 3182, 3249, 3254, 3263, 3267, 3275, 3298, 3300, 3354, 3360, 3408, 3421, 3429, 3471, 3481, 3499, 3508, 3535, 3550, 3563, 3576, 3623, 3633, 3681, 3697, 3698, 3704, 3708, 3727, 3745, 3768, 3785, 3810, 3826, 3836, 3837, 3840, 3841, 3868, 3882, 3893, 3897, 3917, 3948, 3949, 3977, 3984, 3994, 3996, 4007, 4027, 4034, 4084, 4092, 4105, 4109, 4214, 4226, 4254, 4262, 4304, 4306, 4316, 4327, 4340, 4351, 4369, 4386, 4438, 4448, 4571, 4587, 4599, 4624, 4626, 4629, 4641, 4645, 4661, 4678, 4720, 4774, 4800, 4846, 4850, 4855, 4878, 4886, 4896, 4909, 4963, 4975, 4979, 4987, 4993, 5165, 5294, 5308, 5346, 5349, 5378, 5418, 5438, 5445, 5459, 5464, 5479, 5500, 5582, 5585, 5588, 5618, 5640, 5650, 5669, 5673, 5679, 5693, 5749, 5903, 5952, 5988, 5989, 6203, 6218, 6219, 6242, 6283, 6327, 6333, 6365, 6375, 6378, 6395, 6461, 6503, 6539, 6620, 6629, 6638, 6659, 6678, 6707, 6721, 6731, 6744, 6755, 6807, 6820, 6857, 6863, 6874, 6963, 7000, 7028, 7090, 7118, 7123, 7153, 7308, 7360, 7387, 7438, 7454, 7482, 7492, 7561, 7569, 7650, 7802, 8016, 8147, 8157, 8266, 8340, 8368, 8370, 8426, 8501, 8507, 8581, 8636, 8798, 8874, 8910, 8961, 27317, 27873, 31696, 10, 11, 29, 32, 36, 39, 44, 45, 89, 111, 112, 185, 196, 208, 288, 292, 293, 318, 322, 329, 357, 380, 435, 440, 451, 454, 471, 474, 529, 541, 551, 555, 588, 589, 610, 671, 728, 748, 750, 798, 838, 858, 898, 899, 903, 904, 908, 909, 910, 912, 913, 920, 921, 924, 926, 928, 930, 933, 944, 955, 1028, 1036, 1037, 1061, 1077, 1078, 1079, 1082, 1086, 1100, 1101, 1104, 1129, 1178, 1179, 1180, 1193, 1199, 1200, 1201, 1204, 1207, 1212, 1215, 1221, 1225, 1227, 1228, 1230, 1231, 1233, 1234, 1235, 1237, 1238, 1243, 1244, 1247, 1248, 1250, 1252, 1253, 1254, 1257, 1259, 1260, 1261, 1262, 1263, 1267, 1269, 1274, 1276, 1285, 1287, 1288, 1292, 1299, 1301, 1303, 1304, 1307, 1320, 1333, 1356, 1358, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1387, 1388, 1389, 1394, 1464, 1466, 1476, 1485, 1518, 1527, 1544, 1556, 1562, 1584, 1590, 1597, 1610, 1653, 1663, 1674, 1690, 1704, 1719, 1729, 1747, 1748, 1754, 1779, 1784, 1831, 1858, 1876, 1884, 1885, 1917, 1921, 1923, 1924, 1934, 1945, 1950, 1952, 1953, 1956, 1957, 1958, 1963, 1965, 1968, 1997, 2001, 2009, 2010, 2021, 2023, 2034, 2065, 2081, 2100, 2110, 2111, 2117, 2124, 2132, 2144, 2150, 2160, 2181, 2186, 2194, 2202, 2203, 2204, 2243, 2278, 2288, 2289, 2300, 2301, 2302, 2311, 2313, 2321, 2324, 2331, 2346, 2355, 2376, 2391, 2393, 2396, 2402, 2403, 2407, 2409, 2410, 2411, 2412, 2413, 2421, 2454, 2455, 2456, 2476, 2524, 2526, 2527, 2550, 2581, 2599, 2613, 2642, 2643, 2660, 2662, 2664, 2668, 2683, 2693, 2699, 2726, 2729, 2731, 2736, 2746, 2750, 2762, 2779, 2788, 2791, 2795, 2802, 2804, 2815, 2851, 2870, 2871, 2890, 2901, 2908, 2915, 2918, 2921, 2951, 2966, 2968, 2973, 2989, 3006, 3020, 3022, 3032, 3037, 3039, 3068, 3070, 3072, 3082, 3095, 3104, 3108, 3152, 3160, 3174, 3178, 3200, 3201, 3208, 3210, 3244, 3255, 3265, 3269, 3358, 3361, 3362, 3363, 3384, 3396, 3398, 3405, 3418, 3421, 3445, 3462, 3469, 3471, 3481, 3499, 3503, 3504, 3507, 3508, 3529, 3551, 3552, 3608, 3619, 3633, 3635, 3638, 3658, 3681, 3683, 3685, 3697, 3698, 3699, 3730, 3760, 3763, 3767, 3770, 3788, 3801, 3812, 3813, 3814, 3832, 3834, 3846, 6460, 32, 364, 588, 589, 594, 610, 745, 858, 908, 924, 1022, 1027, 1036, 1200, 1215, 1221, 1248, 1276, 1287, 1387, 1394, 1527, 1584, 1610, 1729, 1862, 1907, 1921, 1968, 1994, 2080, 2081, 2085, 2118, 2342, 2391, 2599, 2762, 2912, 3000, 3019, 3178, 3213, 3328, 3362, 3418, 3481, 3745, 3911, 2, 5, 10, 12, 13, 17, 21, 32, 34, 43, 48, 73, 87, 95, 111, 125, 141, 150, 153, 158, 161, 205, 239, 249, 253, 256, 266, 273, 317, 318, 329, 337, 339, 344, 354, 355, 364, 370, 377, 380, 383, 410, 412, 420, 432, 440, 466, 474, 520, 524, 534, 539, 541, 551, 575, 585, 586, 587, 588, 589, 594, 595, 597, 616, 647, 688, 711, 750, 765, 783, 784, 785, 788, 802, 813, 838, 879, 880, 899, 904, 908, 912, 920, 924, 952, 953, 963, 968, 969, 986, 991, 1005, 1007, 1008, 1010, 1011, 1012, 1013, 1015, 1016, 1017, 1019, 1020, 1021, 1022, 1027, 1028, 1035, 1036, 1061, 1064, 1078, 1079, 1083, 1084, 1093, 1094, 1101, 1125, 1126, 1128, 1129, 1130, 1135, 1148, 1179, 1186, 1193, 1194, 1199, 1200, 1201, 1204, 1215, 1225, 1231, 1234, 1242, 1246, 1247, 1250, 1252, 1253, 1257, 1259, 1261, 1262, 1263, 1266, 1269, 1272, 1276, 1283, 1286, 1287, 1288, 1290, 1292, 1297, 1299, 1302, 1304, 1307, 1320, 1321, 1327, 1339, 1343, 1345, 1347, 1350, 1356, 1357, 1367, 1371, 1372, 1373, 1374, 1375, 1376, 1380, 1387, 1388, 1389, 1391, 1393, 1394, 1409, 1425, 1485, 1499, 1513, 1515, 1527, 1544, 1547, 1550, 1562, 1566, 1584, 1588, 1591, 1592, 1603, 1610, 1614, 1616, 1641, 1646, 1653, 1660, 1663, 1665, 1673, 1674, 1682, 1693, 1704, 1711, 1713, 1721, 1722, 1747, 1748, 1754, 1784, 1806, 1821, 1848, 1873, 1883, 1909, 1919, 1923, 1924, 1947, 1952, 1953, 1956, 1957, 1958, 1960, 1961, 1962, 1965, 1968, 1969, 1974, 1982, 1983, 1984, 1994, 1995, 2001, 2002, 2003, 2004, 2009, 2011, 2013, 2014, 2015, 2016, 2020, 2021, 2034, 2035, 2040, 2043, 2050, 2051, 2052, 2053, 2055, 2057, 2064, 2065, 2072, 2077, 2080, 2081, 2083, 2085, 2087, 2089, 2091, 2095, 2097, 2098, 2100, 2108, 2109, 2110, 2111, 2112, 2114, 2117, 2118, 2120, 2121, 2122, 2123, 2124, 2133, 2134, 2135, 2136, 2142, 2144, 2146, 2147, 2150, 2152, 2163, 2176, 2194, 2236, 2241, 2243, 2245, 2248, 2259, 2286, 2289, 2294, 2300, 2301, 2311, 2312, 2313, 2316, 2321, 2324, 2336, 2347, 2352, 2355, 2359, 2365, 2367, 2369, 2371, 2372, 2373, 2374, 2375, 2376, 2378, 2379, 2380, 2384, 2391, 2393, 2396, 2400, 2401, 2402, 2403, 2404, 2405, 2407, 2409, 2410, 2411, 2412, 2416, 2418, 2420, 2421, 2423, 2424, 2429, 2454, 2455, 2456, 2458, 2460, 2462, 2463, 2471, 2473, 2496, 2498, 2501, 2517, 2518, 2524, 2526, 2527, 2530, 2531, 2532, 2533, 2535, 2537, 2539, 2551, 2567, 2613, 2615, 2642, 2643, 2662, 2664, 2668, 2687, 2699, 2701, 2710, 2717, 2719, 2720, 2728, 2734, 2739, 2745, 2759, 2762, 2770, 2779, 2786, 2788, 2791, 2792, 2794, 2795, 2796, 2804, 2805, 2846, 2851, 2852, 2857, 2863, 2866, 2867, 2871, 2875, 2890, 2901, 2902, 2903, 2915, 2918, 2919, 2921, 2922, 2946, 2951, 2966, 2976, 2989, 2990, 3006, 3015, 3016, 3018, 3020, 3036, 3037, 3039, 3040, 3044, 3048, 3054, 3060, 3070, 3074, 3081, 3082, 3087, 3095, 3098, 3100, 3101, 3104, 3105, 3107, 3108, 3114, 3115, 3156, 3157, 3159, 3161, 3167, 3169, 3174, 3175, 3189, 3198, 3204, 3210, 3213, 3244, 3250, 3255, 3256, 3260, 3263, 3269, 3271, 3308, 3313, 3317, 3331, 3342, 3345, 3347, 3354, 3359, 3360, 3361, 3362, 3363, 3368, 3396, 3397, 3418, 3421, 3424, 3471, 3476, 3481, 3483, 3494, 3498, 3499, 3500, 3506, 3507, 3508, 3519, 3524, 3525, 3526, 3543, 3551, 3552, 3572, 3591, 3608, 3614, 3623, 3633, 3635, 3638, 3649, 3654, 3668, 3672, 3676, 3681, 3688, 3689, 3690, 3698, 3699, 3704, 3708, 3751, 3753, 3755, 3763, 3766, 3767, 3769, 3770, 3771, 3784, 3785, 3798, 3806, 3812, 3827, 3833, 3836, 3846, 3863, 3868, 3869, 3873, 3893, 3897, 3916, 3917, 3918, 3926, 3927, 3928, 3930, 3937, 3948, 3957, 3959, 3964, 3971, 3974, 3980, 3984, 3985, 3994, 3998, 4000, 4002, 4005, 4008, 4009, 4010, 4011, 4016, 4019, 4022, 4023, 4027, 4036, 4041, 4042, 4043, 4047, 4062, 4110, 4121, 4148, 4226, 4238, 4239, 4306, 4321, 4329, 4343, 4344, 4370, 4412, 4443, 4459, 4467, 4473, 4480, 4492, 4506, 4522, 4535, 4571, 4587, 4643, 4709, 4719, 4720, 4776, 4815, 4816, 4848, 4865, 4874, 4880, 4881, 4886, 4890, 4896, 4898, 4916, 4941, 4953, 4963, 4966, 4975, 4976, 4979, 4987, 4992, 4993, 4994, 4995, 5015, 5025, 5040, 5048, 5064, 5065, 5103, 5171, 5267, 5299, 5349, 5377, 5378, 5388, 5410, 5418, 5428, 5445, 5459, 5462, 5464, 5497, 5505, 5522, 5528, 5543, 5544, 5618, 5630, 5638, 5679, 5680, 5784, 5816, 5881, 5902, 5944, 5945, 5952, 5954, 5957, 5989, 6003, 6012, 6059, 6157, 6239, 6297, 6303, 6305, 6333, 6337, 6373, 6377, 6378, 6534, 6539, 6565, 6593, 6617, 6620, 6629, 6645, 6708, 6711, 6753, 6755, 6765, 6786, 6873, 6874, 6936, 6942, 6947, 6958, 6959, 7028, 7090, 7143, 7147, 7149, 7150, 7151, 7153, 7158, 7162, 7163, 7254, 7255, 7293, 7324, 7325, 7347, 7361, 7362, 7367, 7380, 7438, 7619, 8360, 8361, 8368, 8372, 8376, 8464, 8528, 8636, 8640, 8641, 8665, 8781, 8783, 8784, 8807, 8874, 8879, 8880, 8908, 8910, 8949, 8959, 8961, 8965, 8970, 8972, 8984, 27618, 27788, 30810, 30822, 30825, 31427, 31700, 31923, 32009, 32011, 32031, 32587, 32598, 33004, 33164, 33166, 33493, 33679, 33794, 34048, 34072, 34162, 34323, 34437, 34528, 34532, 35836, 35957, 36401, 36509, 36527, 37729, 37736, 39183, 39292, 39400, 39414, 39444, 40583, 40629, 40815, 40819, 40959, 42004, 42007, 42011, 42015, 42418, 42732, 43460, 43869, 44195, 45028, 45440, 45447, 45499, 45501, 45517, 45668, 45722, 46967, 47261, 47610, 47950, 48082, 48304, 48385, 48414, 48416, 48696, 48780, 50872, 52319, 52722, 53125, 53519, 53953, 54001, 54503, 54995, 54997, 55768, 56145, 56174, 56339, 57669, 58559, 58839, 58998, 59315, 59369, 59501, 60069, 60126, 60514, 60760, 63082, 68358, 68954, 69122, 72998, 10, 44, 69, 153, 170, 337, 353, 377, 380, 442, 541, 589, 858, 880, 924, 1036, 1079, 1101, 1129, 1200, 1221, 1259, 1343, 1356, 1371, 1372, 1374, 1375, 1376, 1387, 1391, 1394, 1407, 1527, 1562, 1584, 1608, 1610, 1614, 1616, 1641, 1645, 1653, 1663, 1687, 1717, 1722, 1792, 1801, 1833, 1876, 1909, 1917, 1968, 1997, 2006, 2021, 2023, 2126, 2160, 2167, 2194, 2278, 2393, 2396, 2490, 2531, 2533, 2600, 2668, 2683, 2706, 2707, 2710, 2762, 2763, 2791, 2840, 2841, 2871, 2918, 2989, 3081, 3082, 3101, 3107, 3175, 3219, 3249, 3256, 3301, 3438, 3552, 3623, 3633, 3698, 3704, 3751, 3753, 3763, 3791, 3996, 4002, 4005, 4011, 4014, 4015, 4025, 4027, 4085, 4128, 4148, 4262, 4299, 4367, 4369, 4370, 4446, 4571, 4643, 4718, 4734, 4814, 4855, 4874, 4887, 4963, 5049, 5292, 6537, 5, 7, 11, 19, 21, 32, 39, 62, 65, 69, 88, 104, 107, 112, 150, 165, 172, 173, 180, 185, 186, 248, 252, 261, 292, 317, 329, 338, 344, 357, 364, 368, 370, 380, 413, 435, 440, 466, 474, 520, 541, 546, 551, 569, 586, 587, 588, 589, 594, 595, 597, 639, 671, 765, 778, 783, 784, 785, 788, 832, 849, 852, 858, 903, 924, 934, 1005, 1020, 1021, 1028, 1033, 1035, 1036, 1037, 1059, 1101, 1221, 1225, 1242, 1246, 1259, 1285, 1302, 1307, 1356, 1367, 1370, 1371, 1372, 1374, 1375, 1376, 1390, 1391, 1393, 1407, 1431, 1442, 1457, 1476, 1485, 1527, 1566, 1569, 1584, 1591, 1608, 1610, 1615, 1639, 1641, 1642, 1653, 1682, 1688, 1704, 1721, 1729, 1753, 1769, 1784, 1862, 1863, 1866, 1883, 1909, 1921, 1923, 1934, 1961, 1968, 2006, 2011, 2021, 2042, 2052, 2064, 2080, 2081, 2082, 2083, 2087, 2106, 2108, 2124, 2140, 2195, 2231, 2302, 2311, 2324, 2355, 2396, 2407, 2431, 2485, 2501, 2504, 2541, 2598, 2605, 2606, 2672, 2683, 2687, 2694, 2706, 2707, 2710, 2712, 2718, 2731, 2746, 2762, 2763, 2771, 2791, 2804, 2841, 2890, 2915, 2918, 3004, 3082, 3087, 3114, 3175, 3177, 3196, 3248, 3249, 3254, 3255, 3258, 3268, 3269, 3270, 3274, 3285, 3298, 3301, 3360, 3385, 3387, 3394, 3396, 3408, 3421, 3481, 3484, 3510, 3534, 3536, 3549, 3552, 3555, 3565, 3717, 3752, 3753, 3798, 3897, 3911, 3972, 3996, 4011, 4016, 4022, 4033, 4034, 4104, 4299, 4306, 4308, 4369, 4502, 4623, 4638, 4718, 4734, 4886, 4896, 4901, 4929, 4958, 4963, 4974, 4979, 4980, 4993, 5103, 5151, 5218, 5220, 5283, 5307, 5308, 5313, 5349, 5378, 5418, 5445, 5481, 5500, 5502, 5528, 5568, 5582, 5585, 5589, 5620, 5630, 5989, 6287, 6333, 6365, 6373, 6377, 6539, 7173, 7294, 8360, 8528, 8636, 8665, 33004, 33145, 33493, 33495, 33679, 50872, 51080, 53121, 53125, 53322, 53993, 53996, 54272, 54286]

In [57]:
#حالا این فیلم هارا میشماریم و فیلم هایی ک بیشترین تکرار را
#دارند ۱۰ تای اول رو پیشنهاد میدهیم
movie_counts = pd.Series(new_candidate_movies).value_counts()
#print(movie_counts)
top_10=movie_counts[:10]
#print(top_10)

In [58]:
for movie_id, count in top_10.items():

    title = movies.loc[
        movies["movieId"] == movie_id,
        "title"
    ].iloc[0]

    print(title, "→", count, "نفر")

Breakfast Club, The (1985) → 10 نفر
Hunt for Red October, The (1990) → 10 نفر
Die Hard (1988) → 10 نفر
2001: A Space Odyssey (1968) → 10 نفر
Terminator 2: Judgment Day (1991) → 10 نفر
Aliens (1986) → 9 نفر
Star Trek III: The Search for Spock (1984) → 9 نفر
Sixth Sense, The (1999) → 9 نفر
Airplane! (1980) → 9 نفر
Star Trek II: The Wrath of Khan (1982) → 9 نفر

In [62]:
#ساخت تابع برای این موضوع
def recommend_movies(user_id):
    user_index=user_movie_matrix.index.get_loc(user_id)
    similar_users = list(
    enumerate(user_similarity[user_index])
    )

    similar_users = sorted(
    similar_users,
    key=lambda x: x[1],
    reverse=True
    )

    similar_users = similar_users[1:11]
    top_10_users = []

    for index, similarity in similar_users:
        similar_user_id = user_movie_matrix.index[index]
    
        top_10_users.append(similar_user_id)
    candidate_movies = []
    for similar_user in top_10_users:
        user_movies = user_movie_matrix.loc[user_id].dropna().index
        candidate_movies.extend(user_movies)
        
    user_movies = user_movie_matrix.loc[user_id].dropna().index
    new_candidate_movies = []

    for movie_id in candidate_movies:
    
        if movie_id not in user_1_movies:
        
            new_candidate_movies.append(movie_id)
    movie_counts = pd.Series(new_candidate_movies).value_counts()
    top_10=movie_counts[:10]
    
    for movie_id, count in top_10.items():

        title = movies.loc[
            movies["movieId"] == movie_id,
            "title"
        ].iloc[0]
        print(
            title,
            "→",
            count,
            

        )

In [63]:
recommend_movies(50)

Twelve Monkeys (a.k.a. 12 Monkeys) (1995) → 10 نفر از کاربران مشابه
Looper (2012) → 10 نفر از کاربران مشابه
Good Day to Die Hard, A (2013) → 10 نفر از کاربران مشابه
Django Unchained (2012) → 10 نفر از کاربران مشابه
Life of Pi (2012) → 10 نفر از کاربران مشابه
Flight (2012) → 10 نفر از کاربران مشابه
Argo (2012) → 10 نفر از کاربران مشابه
Hotel Transylvania (2012) → 10 نفر از کاربران مشابه
Samsara (2011) → 10 نفر از کاربران مشابه
Great Gatsby, The (2013) → 10 نفر از کاربران مشابه